// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1x1bPVXg9d_oaU9BVoC8_nfInUyc_DFM',
    appId: '1:801481311478:web:16ed85c9e47b015b4518d7',
    messagingSenderId: '801481311478',
    projectId: 'trackit-ef166',
    authDomain: 'trackit-ef166.firebaseapp.com',
    storageBucket: 'trackit-ef166.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSrOeBxS--CX-AXgUKuxdTRdJNRNdmbLM',
    appId: '1:801481311478:android:01d910a1663a5e494518d7',
    messagingSenderId: '801481311478',
    projectId: 'trackit-ef166',
    storageBucket: 'trackit-ef166.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4gehpiP7kaPBHaN47ubgjhCZqpR5VW5U',
    appId: '1:801481311478:ios:0799c1a622c758784518d7',
    messagingSenderId: '801481311478',
    projectId: 'trackit-ef166',
    storageBucket: 'trackit-ef166.appspot.com',
    iosBundleId: 'com.example.trackMoneyApp',
  );
}
